bump_version: null
lint: null
nf_core_version: 3.0.1
org_path: ./modules
repository_type: pipeline
template:
  author: Gabriel Barrett
  description: dDocent workflow
  force: false
  is_nfcore: true
  name: radseq
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null
